project_id = "dwtqshfkewaagjvnbaeo"

[functions.fetch-sheets-data]
verify_jwt = false

[functions.fetch-especialidades-data]
verify_jwt = false

[functions.fetch-om-data]
verify_jwt = false

[functions.fetch-pracas-data]
verify_jwt = false

[functions.fetch-ttc-data]
verify_jwt = false